apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: apps
spec:
  template:
    metadata:
      labels:
        usage: "eks"
        nodepool: "apps"
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: apps
      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["2", "4"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
