apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: alb
spec:
  scheme: internet-facing
  group:
    name: apps
  ipAddressType: ipv4
  subnets:
    matchTags:
      - key: kubernetes.io/role/internal-elb
        value: "1"
      - key: SubnetType
        value: "Private"
  tags:
    cluster: "test"
    environment: "test"
    usage: "eks"
