apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: alb
spec:
  scheme: internet-facing
  group:
    name: apps
  ipAddressType: ipv4
  subnets:
    matchTags:
      - key: kubernetes.io/role/elb
        values: ["1"]
      - key: SubnetType
        values: ["Public"]
  tags:
    - key: cluster
      value: "test"
    - key: environment
      value: "test"
    - key: usage
      value: "eks"
    - key: ingressclass
      value: "alb"
