apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  users.anonymous.enabled: "false"
  admin.enabled: "true"

  # kustomize custom options
  kustomize.buildOptions: --enable-helm --load-restrictor LoadRestrictionsNone

  # https://argo-cd.readthedocs.io/en/stable/user-guide/resource_tracking/
  application.instanceLabelKey: argocd.argoproj.io/instance
