apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow
spec:
  secretStoreRef:
    name: aws
    kind: ClusterSecretStore
  refreshInterval: 0h
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: airflow
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
